### PR TITLE
fix transfer form shows not enough balance incorrectly

### LINKED ISSUE #1771: send- when sending anything other than a currency mosaic, the UI displays there is not enough balance
When sending anything other than a currency mosaic, UI displays "Not enough balance" even if address has enough mosaic balance .

### PR DESCRIPTION
**Pull request by bassemmagdy**
-fixes  #1771

Current Behavior:
[open link](https://www.loom.com/share/38040f500a0c4c6c945ab60cfca80852)

### CODE REVIEW

File: src/components/AmountInput/AmountInputTs.ts [hunk 1]
```diff
@@ -101,16 +101,14 @@ export class AmountInputTs extends Vue {
...
         const selectedMosaic = this.balanceMosaics.find((m) => m.mosaicIdHex === this.mosaicHex);
         const currentMosaicBalance = selectedMosaic.balance / Math.pow(10, selectedMosaic.divisibility);
-        const balance = this.isCosignatoryMode
-            ? currentMosaicBalance
-            : (selectedMosaic.balance - this.selectedFeeValue) / Math.pow(10, selectedMosaic.divisibility);
+        const balance =
+            this.isCosignatoryMode || selectedMosaic.mosaicIdHex !== this.networkConfiguration.currencyMosaicId
+                ? currentMosaicBalance
+                : (selectedMosaic.balance - this.selectedFeeValue) / Math.pow(10, selectedMosaic.divisibility);
         if (currentMosaicBalance == 0 || balance <= 0) {
```
Comment (cryptoBeliever) [inline src/components/AmountInput/AmountInputTs.ts:108]: Looks like we can change this line to:
```
if (balance <= 0) {
```

could you verify?

**Comment by cryptoBeliever** [comment]
From testing all good :+1:

File: src/components/AmountInput/AmountInputTs.ts (hunk 1 above)
Comment (bassemmagdy) [reply src/components/AmountInput/AmountInputTs.ts]: makes sense, update.

**Review by AnthonyLaw — APPROVED** [review]
