### PR TITLE
fix multisig multilevel signing and rest subscription issue

### LINKED ISSUE #1350: Co-signatory of a (2 of 3) multisig account cannot sign an aggregate bonded tx (for creating a multi-level multisig)
There is a possible issue in Symbol Desktop Wallet where a multisig enabled account cannot sign an aggregate bonded transaction to become a cosignatory of a multi-level multisig account. Now, I'm not sure if this is an issue in the core code or in the desktop client.

Background:
I'm trying to setup a harvesting node on AllNodes, and as part of the process, I have to sign an aggregate bonded transaction created by an account managed by AllNodes. According to the instruction of AllNodes, I should be able to sign this transaction in Symbol Desktop Client by:
1. Go to Home,
2. Click on the aggregate bonded transaction, a transaction details pop-up dialog will be shown,
3. In the transaction details pop-up dialog, click on the confirm button

The problem:
There's no "confirm" button. (See screenshot)
This transaction details is also shown for all of my cosignatory accounts; no confirmation button.

Expected behaviour:
* There should be a confirmation button as seen here: https://docs.symbolplatform.com/guides/aggregate/signing-announced-aggregate-bonded-transactions.html
* A (cosignatory of a) multisig account should be able to sign an aggregate bonded transaction.

Screenshots:
TX Hash in screenshot: [C770144F3EFCC5B82F69F9C7B5DD4555798387D7D4904C276109F4512DDECFA7](http://explorer.symbolblockchain.io/transactions/C770144F3EFCC5B82F69F9C7B5DD4555798387D7D4904C276109F4512DDECFA7)
If more information is needed, I'd be happy to share. 

Screenshot 2021-03-20 at 16 15 45

### PR DESCRIPTION
**Pull request by bassemmagdy**
- resolve #1350
- removed js-joda
- refactored date representation to use moment instead of js-joda

**note that this PR should be merged after that [one](https://github.com/symbol/symbol-sdk-typescript-javascript/pull/800) from symbol-sdk gets merged, after that a new alpha sdk should be release and added here to be fully testable.**

### CODE REVIEW

**Review by AdriaCarrera — DISMISSED** [review]

**Comment by bassemmagdy** [comment]
@NikolaiB @cryptoBeliever sdk-version got pumped, PR should be ready for testing.

File: src/components/TransactionList/TransactionRow/TransactionRowTs.ts [hunk 1]
```diff
@@ -456,27 +466,19 @@ export class TransactionRowTs extends Vue {
...
-            .format(DateTimeFormatter.ofPattern('yyyy-MM-dd HH:mm:ss'));
-    }
     public get date() {
         if (this.transaction instanceof AggregateTransaction) {
-            return this.transaction.deadline
-                .toLocalDateTime(this.networkConfiguration.epochAdjustment)
-                .minusHours(48)
-                .format(DateTimeFormatter.ofPattern('yyyy-MM-dd HH:mm:ss'));
+            return moment(
+                String(this.transaction.deadline.toLocalDateTime(this.networkConfiguration.epochAdjustment).minusHours(48)),
```
Comment (AnthonyLaw) [inline src/components/TransactionList/TransactionRow/TransactionRowTs.ts:472]: seem there is a few repeated codes.
It will be great, create a method in the `TimeHelpers` class.

File: src/store/Account.ts [hunk 2]
```diff
@@ -406,8 +412,8 @@ export default {
                     .getMultisigAccountGraphInfo(currentAccountAddress)
                     .pipe(
                         map((g) => {
-                            // sorted array to be represented in multisig tree
                             commit('multisigAccountGraph', g.multisigEntries);
+                            commit('multisigAccountGraphInfo', MultisigService.getMultisigInfoFromMultisigGraphInfo(g));
                             return MultisigService.getMultisigInfoFromMultisigGraphInfo(g);
```
Comment (AnthonyLaw) [inline src/store/Account.ts:417]: it called the same function twice, 
`const x = MultisigService.getMultisigInfoFromMultisigGraphInfo(g)` will look clean.

File: src/store/Transaction.ts [hunk 3]
```diff
@@ -226,6 +228,12 @@ export default {
             }
 
             state.filteredTransactions = TransactionFilterService.filter(state, currentSignerAddress);
+            if (!!multisigAddresses.length) {
+                multisigAddresses.forEach((address) => {
+                    state.filteredTransactions = [...state.filteredTransactions, ...TransactionFilterService.filter(state, address)];
+                });
+                state.filteredTransactions = TransactionFilterService.filter(state, currentSignerAddress);
```
Comment (AnthonyLaw) [inline src/store/Transaction.ts:235]: `state.filteredTransactions = TransactionFilterService.filter(state, currentSignerAddress);`

it called inside and outside if statement. you should refactor it.

File: src/store/Transaction.ts [hunk 4]
```diff
@@ -285,6 +293,12 @@ export default {
             const subscriptions: Observable<Transaction[]>[] = [];
             commit('isFetchingTransactions', true);
 
+            const multisigAccountGraphInfo: MultisigAccountInfo[][] = rootGetters['account/multisigAccountGraphInfo'];
```
Comment (AnthonyLaw) [inline src/store/Transaction.ts:296]: I saw the interface `account/multisigAccountGraphInfo` is created `MultisigAccountInfo[];` single array.

why over here is a 2D array?

File: src/core/utils/CommonHelpers.ts [hunk 5]
```diff
@@ -47,4 +47,13 @@ export class CommonHelpers {
             await this.sleep(interval);
         }
     }
+    public static parseObjectProperties(obj, parse): void {
```
Comment (AnthonyLaw) [inline src/core/utils/CommonHelpers.ts:50]: The params `parse` type is `any`, I'm not sure it's a good idea.
my suggestion will be a method in helper class should return something we can predict.

**Review by AnthonyLaw — COMMENTED** [review]
please add those new methods to the unit test as well.

File: src/store/Transaction.ts (hunk 4 above)
Comment (bassemmagdy) [reply src/store/Transaction.ts:296]: because it refers to Multisig entries which is a 2D array of multisigAccountInfo

File: src/store/Transaction.ts (hunk 3 above)
Comment (bassemmagdy) [reply src/store/Transaction.ts:235]: condition added to make sure partial transactions needs to be signed always shows up first thing on the list

File: __tests__/services/MultisigService.spec.ts [hunk 6]
```diff
@@ -14,14 +14,31 @@
...
         test('return multisig info contained in a multisig graph', () => {
             const multisigsInfo = MultisigService.getMultisigInfoFromMultisigGraphInfo(multisigGraphInfo1);
             expect(multisigsInfo).toStrictEqual([...multisigEntries1, ...multisigEntries2]);
         });
     });
+
+    describe('getMultisigChildren() should', () => {
+        test('return multisigChildren', () => {
+            const multisigChildren = multisignService.getMultisigChildren([multisigEntries3]);
+            console.log(multisignService.getMultisigChildrenAddresses([multisigEntries3]));
```
Comment (AnthonyLaw) [inline __tests__/services/MultisigService.spec.ts:33]: remove console.log

File: __tests__/services/MultisigService.spec.ts [hunk 7]
```diff
@@ -14,14 +14,31 @@
  *
  */
 
-import { multisigEntries1, multisigEntries2, multisigGraphInfo1 } from '@MOCKS/multisigGraphInfo';
+import { multisigEntries1, multisigEntries2, multisigEntries3, multisigGraphInfo1 } from '@MOCKS/multisigGraphInfo';
 import { MultisigService } from '@/services/MultisigService';
 
 describe('services/MultisigService', () => {
+    const multisignService = new MultisigService();
```
Comment (AnthonyLaw) [inline __tests__/services/MultisigService.spec.ts:21]: method `getMultisigChildrenAddresses` is missing on test.

File: __mocks__/multisigGraphInfo.ts [hunk 8]
```diff
@@ -105,6 +105,17 @@ export const multisigEntries2 = multisigAccountGraphInfoDTO2.multisigEntries.map
...
 );
 
+export const multisigEntries3 = multisigAccountGraphInfoDTO.multisigEntries.map(
+    (multisigAccountInfoDTO) =>
+        new MultisigAccountInfo(
+            1,
+            multisigAccountInfoDTO.multisig.accountAddress,
+            multisigAccountInfoDTO.multisig.minApproval,
+            multisigAccountInfoDTO.multisig.minRemoval,
+            [],
```
Comment (AnthonyLaw) [inline __mocks__/multisigGraphInfo.ts:115]: just wondering, in `cosignatoryAddresses` it should contain a multisig account, right?
to build multi-level multisig?

File: __tests__/services/MultisigService.spec.ts (hunk 7 above)
Comment (bassemmagdy) [reply __tests__/services/MultisigService.spec.ts:21]: it just consumes getMultisigChildren so I though it doesn't need a separate test case.

File: __mocks__/multisigGraphInfo.ts (hunk 8 above)
Comment (bassemmagdy) [reply __mocks__/multisigGraphInfo.ts:115]: yes, but having multisig addresses would let the account be a multisig one resulting empty array of children.

File: __tests__/services/MultisigService.spec.ts (hunk 7 above)
Comment (AnthonyLaw) [reply __tests__/services/MultisigService.spec.ts:21]: best practice should have all the methods in the test.
So next time for other dev can easily follow up and understand.

File: src/core/utils/CommonHelpers.ts [hunk 9]
```diff
@@ -47,4 +47,18 @@ export class CommonHelpers {
             await this.sleep(interval);
         }
     }
+    /**
+     * Traverses the tree object to pick addresses strings.
+     * @param {array} array of multisig children
+     * @param {parse} function to parse tree and pick children addresses
+     */
+    public static parseObjectProperties(obj: [], parse): void {
```
Comment (AnthonyLaw) [inline src/core/utils/CommonHelpers.ts:55]: add a unit test.

File: src/services/MultisigService.ts [hunk 10]
```diff
@@ -104,6 +110,67 @@ export class MultisigService {
...
+                        );
+                    });
+                }
+            });
+        });
+        return tree;
+    }
+
+    /**
+     * @param {MultisigAccountInfo[][]} multisigEnteries
```
Comment (AnthonyLaw) [inline src/services/MultisigService.ts:157]: missing method definition

File: __tests__/utils/ComonHelpers.spec.ts [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and limitations under the License.
+ *
+ */
+import { CommonHelpers } from '@/core/utils/CommonHelpers';
+import { MultisigService } from '@/services/MultisigService';
+import { givenParentAccountGraphInfo } from '@MOCKS/multisigGraphInfo';
+import { Address } from 'symbol-sdk';
+
+describe('utils/CommonHelpers', () => {
```
Comment (AnthonyLaw) [inline __tests__/utils/ComonHelpers.spec.ts:21]: filename typo

__tests__/utils/ComonHelpers.spec.ts -> __tests__/utils/CommonHelpers.spec.ts

**Review by AnthonyLaw — DISMISSED** [review]

**Comment by NikolaiB** [comment]
@bassemmagdy I am getting some errors in console while converting simple account into multisig and back
image
image

I am also getting this error in Terminal while building the project:
image

**Comment by bassemmagdy** [comment]
@NikolaiB I've updated the PR, make sure to `npm install `.

**Comment by NikolaiB** [comment]
@bassemmagdy all errors are fixed.

**Comment by AnthonyLaw** [comment]
@bassemmagdy just wondering why the package-lock has so big change?

**Review by AnthonyLaw — APPROVED** [review]
