### PR TITLE
fix #1767

### LINKED ISSUE #1767: Error login - when selected node websockets doesn't work
Looks like it's issue with nodes that don't support webscockets or websockets doesn't work. 

Steps to reproduce:
1. Create profile and connect to node X
2. Close app
3. Shut down node X
4. Open app and login
5. App will detect that node X is down and will switch to other node Y

If node Y will be without working WebSockets user will be not able to login (error below) each time.

Steps to reproduce (easier way for developer):
1. Create profile on mainnet (can be on browser version because it's easier to change local storage data)
2. Open chrome console go to Application -> Local storage -> profiles. Change for profile selectedNodeUrlToConnect to (for example) https://0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-4.symbol-nodes.jp:3001/
3. Close chrome console and try login. Each time failed (for 0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-4.symbol-nodes.jp node WebSockets doesn't work).

image

**Workaround for users**:
- **If user have mnemonics (24 words) backup**: Try create a new profile using mnemonics (24 words) backup. Create a new profile -> Import mnemonics. It should connect to random node which hopefully will have working websockets.
- **If user don't have mnemonics backup**. User should wait until the new version released. 

Also if node has disabled wss web sockets but enabled HTTPS user is not able switch to this node:

image

### PR DESCRIPTION
**Pull request by bassemmagdy**
Currently, when a node allows SSL/port:3001 and does not provide a stable connection for WebSockets subscription the wallet fails to login.

Proposed solution:
fallback for HTTP/port:3000 and retry the connection, in case it fails wallet should fall-back to a different node seeking a valid Websocets connection.

### CODE REVIEW

File: src/services/NetworkService.ts [hunk 1]
```diff
@@ -168,4 +169,18 @@ export class NetworkService {
...
     }
+    /**
+     * It checks if a node has Websocket functioning properly to subscribe.
+     * @param url the url.
+     */
+    public async checkWebsocketConnection(url: string) {
+        const webSocket = new WebSocket(url);
+        let websocketConnectionStatus: boolean = false;
+        webSocket.onmessage = function (e) {
+            // @ts-ignore
```
Comment (OlegMakarenko) [inline src/services/NetworkService.ts:180]: Can we avoid `// @ts-ignore`?

File: src/services/NetworkService.ts [hunk 2]
```diff
@@ -168,4 +169,18 @@ export class NetworkService {
...
+            websocketConnectionStatus = e.currentTarget.readyState == 1;
+        };
+        await CommonHelpers.sleep(2000);
```
Comment (OlegMakarenko) [inline src/services/NetworkService.ts:183]: Why do we need this delay?

File: src/store/Network.ts [hunk 3]
```diff
@@ -311,10 +311,25 @@ export default {
...
                 });
                 nodeNetworkModelResult = await networkService.getNetworkModel(newCandidateUrl, networkType, isOffline).toPromise();
+                let wsUrl = undefined;
+                let wsConnection = undefined;
+                if (navigator.onLine && !isOffline) {
+                    wsUrl = nodeNetworkModelResult.repositoryFactory.createListener().url;
+                    wsConnection = await networkService.checkWebsocketConnection(wsUrl);
+                    if (!wsConnection.status && wsConnection.sslNode) {
+                        nodeNetworkModelResult = await networkService
+                            .getNetworkModel(newCandidateUrl.replace('https', 'http').replace('3001', '3000'), networkType, isOffline)
```
Comment (OlegMakarenko) [inline src/store/Network.ts:321]: I think ports should not be hardcoded and returned by statistics-service

Comment (bassemmagdy) [reply src/store/Network.ts:321]: this is for the fallback case, sometimes the node allows WS connection on  port 3000 but not 3001, while the node itself is providing ssl connection, so we need to replace the returned one and retry.

File: src/services/NetworkService.ts (hunk 2 above)
Comment (bassemmagdy) [reply src/services/NetworkService.ts:183]: to make sure readyState has the correct value returned from the function.

File: src/services/NetworkService.ts (hunk 1 above)
Comment (bassemmagdy) [reply src/services/NetworkService.ts:180]: it's needed here to skip the linter check.

Screen Shot 2021-11-15 at 6 11 08 PM

Comment (yilmazbahadir) [reply src/services/NetworkService.ts:180]: maybe arrow function with the parameter type(at least `any`)?

File: src/services/NetworkService.ts [hunk 4]
```diff
@@ -168,4 +169,18 @@ export class NetworkService {
                   websocketInjected: WebSocket,
               });
     }
+    /**
+     * It checks if a node has Websocket functioning properly to subscribe.
+     * @param url the url.
+     */
+    public async checkWebsocketConnection(url: string) {
```
Comment (yilmazbahadir) [inline src/services/NetworkService.ts:176]: can we add a return type?

File: src/services/NetworkService.ts (hunk 2 above)
Comment (yilmazbahadir) [reply src/services/NetworkService.ts:183]: Can we replace `2000` with a timeout parameter here? (which is defaulted to `2000`)

File: src/store/Network.ts [hunk 5]
```diff
@@ -340,10 +355,29 @@ export default {
...
+                                .getNetworkModel(
+                                    currentProfile.selectedNodeUrlToConnect.replace('https', 'http').replace('3001', '3000'),
+                                    networkType,
+                                    isOffline,
+                                )
+                                .toPromise();
+                            wsUrl = nodeNetworkModelResult.repositoryFactory.createListener().url;
+                            wsConnection = await networkService.checkWebsocketConnection(wsUrl);
+                        }
+                    }
```
Comment (yilmazbahadir) [inline src/store/Network.ts:374]: This code block seems to be duplicated. Is it possible to extract this block to an inline arrow function that returns a tuple and use both here(`else` part) and the `if` part?

File: src/services/NetworkService.ts [hunk 6]
```diff
@@ -168,4 +169,18 @@ export class NetworkService {
...
+        const webSocket = new WebSocket(url);
+        let websocketConnectionStatus: boolean = false;
+        webSocket.onmessage = function (e) {
+            // @ts-ignore
+            websocketConnectionStatus = e.currentTarget.readyState == 1;
+        };
+        await CommonHelpers.sleep(2000);
+        return { status: websocketConnectionStatus, sslNode: url.indexOf(':3001') !== -1 };
```
Comment (yilmazbahadir) [inline src/services/NetworkService.ts:184]: Would be nice to extract `3000` and `3001` to constants and all references to them.

**Comment by AnthonyLaw** [comment]
I had created the PR related to the WebSocket issue.
https://github.com/symbol/statistics-service/pull/108

Should we wait for this merge then only update the wallet apps?

File: src/store/Network.ts (hunk 5 above)
Comment (bassemmagdy) [reply src/store/Network.ts]: I did refactor this applying the changes in network service.

File: src/services/NetworkService.ts (hunk 4 above)
Comment (bassemmagdy) [reply src/services/NetworkService.ts]: Added

**Comment by cryptoBeliever** [comment]
I tested following scenario (which I think works on 1.0.8)

1. Choose node X in profile Y
2. Close app
3. Stop node X
4. Open app and try login to profile Y

Result: Login is not possible (same error as previously)

===

Other issue is that if we have "broken" node and it will be returned by statistics service then we are also unable to login because /network/fees/transaction failing. You can simulate by setting node https://node.finefettle.life:3001/network in local storage as selected node.
Currently this node is broken. Call https://node.finefettle.life:3001/network/fees/transaction returns error 500:

```
https://node.finefettle.life:3001/network/fees/transaction

```
{
"code": "Internal",
"message": "ENOENT: no such file or directory, open '/symbol-workdir/api-node-config/config-node.properties'"
}
```

**Comment by bassemmagdy** [comment]
@cryptoBeliever 

>  I'm wonder what will happen if REST is available only over https (no http)? And no wss:3001 or ws:3000 is available. It will switch to another node?

yes, it should switch to a different node.

for the second scenario if endpoint` network/fees/transaction` returns `500`, if we stopped calling that endpoint on login/import accounts the case when a user has any transactions that need rentalFees like namespaces/mosaics in history we won't be able to display them correctly.

**Review by NikolaiB — DISMISSED** [review]

**Comment by cryptoBeliever** [comment]
> for the second scenario if endpoint `network/fees/transaction` returns `500`, actually we need to call that endpoint on login to be able to display namespaces/mosaics transactions as the wallet needs rental fees to display them correctly.

@bassemmagdy I'm not asking to not call this endpoint but broken node should not block user from login.

File: src/services/NetworkService.ts [hunk 7]
```diff
@@ -168,4 +171,51 @@ export class NetworkService {
...
+    }
+
+    /**
+     * It checks if a node has Websocket functioning properly to subscribe.
+     * @param nodeNetworkModelResult any
+     * @param url the url.
+     * @param networkType
+     * @param isOffline whether user is in offline mode
+     */
+    public async CheckWebSocketConnectionHttpAndHttps(
```
Comment (yilmazbahadir) [inline src/services/NetworkService.ts:198]: starts with uppercase?

**Comment by bassemmagdy** [comment]
@yilmazbahadir after discussion with @cryptoBeliever we agreed to separate the rental Fees [issue](https://github.com/symbol/desktop-wallet/issues/1773) into a new one and to be addressed in a different branch.

**Comment by yilmazbahadir** [comment]
There 2 changes recently made in the statistics service: 

1. NodeInfo.apiStatus.webSocket object https://github.com/symbol/statistics-service/blob/8ea683a3e75591f6de9b04f7f8c106edda36466a/openapi/openapi.yml#L315
2. Filtering secured(HTTPS && WSS) nodes only.

PR https://github.com/symbol/desktop-wallet/pull/1777 integrates statistics-service openapi client with these changes.

We should be using `apiStatus.webSocket.url` instead of falling back to a different websocket protocol logic here.

You will find a new field `wsUrl` in the `NodeModel` class. We should be using that field to connect to a websocket, if not successful then try a different node.

**Review by yilmazbahadir — COMMENTED** [review]
Where do we try to connect to the returned `wsUrl` and check it is not failing?

**Comment by yilmazbahadir** [comment]
We should be using `nodeModel.wsUrl` instead of trying to calculate ourselves here => https://github.com/bassemmagdy/symbol-desktop-wallet/blob/10381d9fd7d16b5b2d4760f53787604cdcc3ca4d/src/services/NetworkService.ts#L181

**Comment by bassemmagdy** [comment]
@yilmazbahadir the issue is it's not available (nodeMode.wsUrl) before creating the nodeModel, which has the createRepositroyFactory() as a part of it, so we could update the HTTPS nodes the same way as we do for HTTP ones.

File: src/services/NetworkService.ts [hunk 8]
```diff
@@ -164,7 +178,7 @@ export class NetworkService {
         return isOffline
             ? new OfflineRepositoryFactory(networkType)
             : new RepositoryFactoryHttp(url, {
-                  websocketUrl: URLHelpers.httpToWsUrl(url) + '/ws',
+                  websocketUrl: url.indexOf('http:') !== -1 ? URLHelpers.httpToWsUrl(url) + '/ws' : URLHelpers.httpsToWsUrl(url) + '/wss',
```
Comment (yilmazbahadir) [inline src/services/NetworkService.ts:181]: Do we really need this and also `httpsToWsUrl`?
It looks like `httpToWsUrl` already replaces `http` with `ws` thus if the protocol is "https" when it is replaced with "ws" it will become "ws**s**", no? And trailer `/wss` looks wrong.

**Comment by yilmazbahadir** [comment]
> @yilmazbahadir the issue is it's not available (nodeMode.wsUrl) before creating the nodeModel, which has the createRepositroyFactory() as a part of it, so we could update the HTTPS nodes the same way as we do for HTTP ones.

Should we change the order of calls instead? 
First call `NodeService.getNodesFromStatisticService` and then the others?

File: src/views/forms/FormNodeEdit/FormNodeEditTs.ts [hunk 9]
```diff
@@ -100,6 +100,9 @@ export class FormNodeEditTs extends Vue {
             }
             this.formItems.networkType = NetworkType[networkModel.networkType];
             this.formItems.networkHash = networkModel.generationHash;
+        } catch (err) {
+            console.log(err);
```
Comment (AnthonyLaw) [inline src/views/forms/FormNodeEdit/FormNodeEditTs.ts:104]: We can use  rather then log `console.error(err)`

**Comment by yilmazbahadir** [comment]
Looks good to me, can be merged after the checks are successful.

**Review by yilmazbahadir — DISMISSED** [review]

**Comment by cryptoBeliever** [comment]
@bassemmagdy 

The following scenario doesn't work again:

1. Choose node X in profile Y
2. Close app
3. Stop node X
4. Open app and try login to profile Y

Result: Login is not possible (same error as previously)

You can simulate node down by manually changing selected node in local storage to non-existent.

**Comment by cryptoBeliever** [comment]
After latest fixes all good :+1:

**Review by cryptoBeliever — APPROVED** [review]
