### PR TITLE
fix the ability to initialize aggregate with single transaction 

### LINKED ISSUE #1803: Not able to initialize aggregate when only one transaction
Affected version: 1.0.8 (It worked in 1.0.7 so something changed in 1.0.8 - probably https://github.com/symbol/desktop-wallet/issues/1748)

Steps:
1. Login to profile
2. Go to Aggregate tab
3. Try init simple aggregate with one transfer transaction

Result Ledger: Not able to sign transaction. Looks like transaction is failing (data corrupted) when trying to transfer to the device.

Result Regular account: Transaction is not announced

Video Ledger: https://share.getcloudapp.com/v1ujkN9o

### PR DESCRIPTION
**Pull request by bassemmagdy**
-fix #1803

### CODE REVIEW

**Comment by cryptoBeliever** [comment]
Works :+1:

**Review by cryptoBeliever — APPROVED** [review]

File: src/views/forms/FormAggregateTransaction/FormAggregateTransactionTs.ts [hunk 1]
```diff
@@ -192,20 +192,22 @@ export class FormAggregateTransactionTs extends FormTransactionBase {
     private createTransferTx(tx: {}): TransferTransaction {
         const maxFee = UInt64.fromUint(this.formItems.maxFee);
         this.formItems.recipientRaw = tx['formItems']['recipientRaw'];
-        const signer = PublicAccount.createFromPublicKey(tx['formItems']['signerPublicKey'], this.networkType);
+        const signer = tx['formItems']['signerPublicKey']
+            ? PublicAccount.createFromPublicKey(tx['formItems']['signerPublicKey'], this.networkType)
+            : undefined;
         const t: TransferTransaction = TransferTransaction.create(
```
Comment (Jaguar0625) [inline src/views/forms/FormAggregateTransaction/FormAggregateTransactionTs.ts:198]: what does TransferTransaction.create do when signer is undefined?

Comment (bassemmagdy) [reply src/views/forms/FormAggregateTransaction/FormAggregateTransactionTs.ts:198]: TransferTransaction.create() doesn't need a signer for the transaction it's an optional parameter, was just using it in case of transactions made via multi-sig accounts.

**Review by Jaguar0625 — APPROVED** [review]
